name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # تغییر از v3 به v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4  # تغییر از v3 به v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4  # تغییر از v3 به v4
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
