name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission
      run: chmod +x gradlew || echo "gradlew not found, will generate it"
      
    - name: Generate gradlew if missing
      run: ./gradlew wrapper || true
      
    - name: Build APK
      run: |
        if [ -f "gradlew" ]; then
          chmod +x gradlew
          ./gradlew assembleDebug
        else
          gradle assembleDebug
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: app/build/outputs/apk/debug/*.apk
